### ISSUE TITLE
Question: Why not use /Applications?

### ISSUE THREAD

**Issue by patgmac** [kc9wwh/macOSUpgrade#1]
I'm curious if there is a reason to not use an already (Apple) cached instance of the Sierra installer? Seems like a large download can be prevented.

**Comment by kc9wwh** [comment]
The only reason we chose not to use the one that could be in the /Applications/ folder is cause that one is "uncontrolled". Meaning...not everyone will have it, if they do have it, it might not even be the latest version. Because of these uncertainties it was opted to deploy a controlled package.

Although (wheels turning) this script could be modified to look for an existing package and verify the version matches what we want, if so it could use that, if not we could easily call a policy to download what we are looking for.

**Comment by patgmac** [comment]
Yea, that's what I'm thinking. I'm doing some additions for this today. I have upwards of 600 machines with the installer already cached from Apple, so I'd like to re-use that.  I'll share what I have when I'm done and you can decided if you want to add it.
