### ISSUE TITLE
loop error - Checksum is Not Valid

### ISSUE THREAD

**Issue by VladKosmos** [kc9wwh/macOSUpgrade#132]
Hi,
Geat script. Thanks for your work.
But from the last apple security update, I've got such error

`Script result: Killing caffeinate processes. No matching processes were found Killing startosinstall processes. No matching processes were found Killing osinstallersetupd processes. No matching processes were found Power Check: OK - AC Power Detected Disk Check: OK - 211791314944 Bytes Free Space Detected Downloading macOS Installer... This policy trigger is already being run: root 5249 38.7 0.2 4399712 33488 ?? S 9:07PM 1:26.76 /usr/local/jamf/bin/jamf policy -event OSMojavePKGinstall Downloading macOS Installer... This policy trigger is already being run: root 5249 34.4 0.2 4399712 33488 ?? S 9:07PM 1:28.26 /usr/local/jamf/bin/jamf policy -event OSMojavePKGinstall Downloading macOS Installer... This policy trigger is already being run: root 5249 32.0 0.2 4399712 33488 ?? S 9:07PM 1:29.62 /usr/local/jamf/bin/jamf policy -event OSMojavePKGinstall macOS Installer Downloaded 3 Times - Checksum is Not Valid Prompting user for error and exiting...
`
Apple pkg was rebuild after apple fixed their problem with certificates in the installation app but the problem still appears. Looks like a loop.

**Comment by taniguti** [comment]
It is expected behavior.
When checksum is not match with one you provided, this script will try download installer up to 3 times.

As you mentioned, Apple has been renewed installer. So, you have to replace installer which will be downloaded by your event, OSMojavePKGinstall. And also update checksum value of parameter 7.

The script `prepare-jamf-policy.sh` in helper-tools dir will help you.
